### ISSUE TITLE
Configs diverses

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/plugin-bornetenda#10]
1 - Mettre à la racine du repo le .editorconfig du plugin template

2 - Mettre à la racine du repo le ISSUE_TEMPLATE.md du plugin template

**Comment by guenneguezt** [comment]
https://github.com/Jeedom-Plugins-Extra/plugin-bornetenda/commit/cbab05d2177b224a0f8e7f5ff67f6a14d1ab611d
