### ISSUE TITLE
Docs au nouveau standard de la team (github pages)

### ISSUE THREAD

**Issue by byackee** [Jeedom-Plugins-Extra/plugin-bornetenda#2]
Utilisation de Github pages, template disponible dans le repo plugin-template de la team

Aller voir le wiki: https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/Documentation-d'un-Plugin

**Comment by guenneguezt** [comment]
Fait : https://github.com/Jeedom-Plugins-Extra/plugin-bornetenda/commit/cbab05d2177b224a0f8e7f5ff67f6a14d1ab611d
