### ISSUE TITLE
Passer les repos au standard Git-Flow

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/plugin-bornetenda#3]
Organiser le repo du plugin en suivant : https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/Gestion-de-sources---Git-&-Co

**Comment by guenneguezt** [comment]
Fait : https://github.com/Jeedom-Plugins-Extra/plugin-bornetenda/commit/cbab05d2177b224a0f8e7f5ff67f6a14d1ab611d
