### ISSUE TITLE
Passer les repos au standard PSR-2

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/plugin-bornetenda#4]
Nettoyer le code en respactant le standard PSR-2 et en suivant : https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/Bonnes-pratiques-pour-les-plugins

**Comment by guenneguezt** [comment]
https://github.com/Jeedom-Plugins-Extra/plugin-bornetenda/commit/cbab05d2177b224a0f8e7f5ff67f6a14d1ab611d
