### ISSUE TITLE
Noms des variables et fonctions

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/plugin-bornetenda#9]
Le nom de toutes les variables et fonctions du plugin doivent respecter la norme yyyyyXyyyy

ex :

envoiInfo

paramTemperature

**Comment by guenneguezt** [comment]
https://github.com/Jeedom-Plugins-Extra/plugin-bornetenda/commit/cbab05d2177b224a0f8e7f5ff67f6a14d1ab611d
